name: lukhisan
layout_spectrum: 0.891544043228104
typography_spectrum: 0.9397268275100517
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#535355'
    - '#000000'
    - '#ADADAD'
    - '#EEEDE8'
    - '#788A24'
  brandStrength: 0.03133091154840249
  lightness: 0.5055540573787829
  saturation: 0.22288172954887078
  rhythmicContrast: 0.6252344495693387
title: photography | photomotion |
description: ' Events, Parties, Corporate, Portraiture,'
author:
  name: Noah Lukhisan
  url: fb.com/lukhisan
  email: Lukhisan@outlook.com
content_rating:
  adult: false
navigation:
  - name: Intro
    id: ea6ba3f5-befd-4681-95f6-bd8626d60937
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: quote
    html: >-
      <blockquote>i do not owe the music , i owe the video of my Lapse
      Journey</blockquote>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.facebook.com/mdno.sg/videos/1063618393683962/'
      keywords: []
      title: ''
      publisher:
        name: Facebook
        domain: www.facebook.com
        url: 'https://www.facebook.com'
        favicon: 'https://www.facebook.com/rsrc.php/yV/r/hzMapiNYYpW.ico'
      author: []
      starred: false
      description: 'i do not owe the music , i owe the video of my Lapse Journey'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: 'i do not owe the music , i owe the video of my Lapse Journey'
github: true
